packages:
  - exercises/01-runtime/reference/apps/*
  - exercises/01-runtime/reference/packages/*
  - exercises/0[3-8]-*/reference
  - exercises/collaboration-board/reference
  - exercises/collaboration-board/reference/apps/*
  - exercises/collaboration-board/reference/packages/*
