apiVersion: v1
kind: Namespace
metadata:
  name: platform-lab
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: checkout
  namespace: platform-lab
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout
  namespace: platform-lab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: checkout
  template:
    metadata:
      labels:
        app: checkout
    spec:
      serviceAccountName: checkout
      containers:
        - name: app
          image: platform-guide/http-echo:v1
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests: {cpu: 25m, memory: 32Mi}
            limits: {cpu: 200m, memory: 64Mi}
          readinessProbe:
            httpGet: {path: /ready, port: http}
          livenessProbe:
            httpGet: {path: /live, port: http}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: {drop: ["ALL"]}
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        seccompProfile: {type: RuntimeDefault}
---
apiVersion: v1
kind: Service
metadata:
  name: checkout
  namespace: platform-lab
spec:
  selector: {app: checkout}
  ports:
    - name: http
      port: 80
      targetPort: http
