CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX users_email_ci_uq ON users (lower(email));

CREATE TABLE projects (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id bigint NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    name text NOT NULL CHECK (btrim(name) <> ''),
    status text NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'ARCHIVED')),
    UNIQUE (owner_id, name)
);

CREATE TABLE memberships (
    project_id bigint NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role text NOT NULL CHECK (role IN ('OWNER', 'EDITOR', 'VIEWER')),
    PRIMARY KEY (project_id, user_id)
);

CREATE TABLE tasks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id bigint NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    assignee_id bigint,
    title text NOT NULL CHECK (btrim(title) <> ''),
    priority integer NOT NULL CHECK (priority BETWEEN 1 AND 5),
    status text NOT NULL CHECK (status IN ('OPEN', 'IN_PROGRESS', 'DONE')),
    completed_at timestamptz,
    FOREIGN KEY (project_id, assignee_id)
        REFERENCES memberships(project_id, user_id)
        ON DELETE RESTRICT,
    CHECK (
        (status = 'DONE' AND completed_at IS NOT NULL)
        OR
        (status <> 'DONE' AND completed_at IS NULL)
    )
);
